name: "\U0001F64B Feature Request"
description: 'Want us to add something to FluentValidation?'
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us make FluentValidation even better! Please fill out this form as thoroughly as possible.
        
        **Please note** FluentValidation is supported for free on a voluntary basis. If you use FluentValidation please [sponsor the project](https://github.com/sponsors/JeremySkinner) so that its development can continue. Feature requests from sponsors will be prioritised.
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context or sample code about the feature request here.
